<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
<table>
    <tr>
        <th>发送人</th>
        <th>内容</th>
        <th>接受</th>
    </tr>
    <tr>
        <td>${message}</td>
        <td>${}</td>
        <td></td>
    </tr>
</table>
</body>
</html>
